### ISSUE TITLE
Examle using rtsp_proxy and svtool

### ISSUE THREAD

**Issue by Sathopper2000** [CFSworks/shrdvr#4]
Try to connect to my SHR-5042 DVR using Python 2.7 
I run the scripts on the command line like: svtool.py --username test --password test  url RTSP://IP off DVR:PORT of DVR
I keep getting an error like:  url {describe,authorize}
Please give an example how to give the right arguments.
Many thanks (y)

**Comment by CFSworks** [comment]
Hi @Sathopper2000!

I no longer have access to the DVR I was bridging with this script, so my ability to debug and troubleshoot is very limited.

The URL is a positional argument, so you don't need to be writing "url" in your command line. You can do either one of these:

`svtool.py --username test --password test rtsp://1.2.3.4:5678/ describe`
`svtool.py rtsp://test:test@1.2.3.4:5678/ describe`

Note that svtool isn't itself really a complete script; it could easily become one if needed, but its main purpose is just to generate an auth cookie for the RTSP proxy to use.

When I wrote the RTSP proxy, I thought the SHR "protocol" (if it can be called that) was just a slight variation on RTSP that I could loosely translate into standard RTSP, but boy was I wrong. Instead, Samsung implements some kind of... "thing" that only vaguely resembles RTSP. So what I ended up putting into this repository turned out to be a pile of hacks that, on my particular DVR, worked perfectly.

You are welcome to slice away at the script and see if you can get it to work on your DVR, but what I had hoped would be an out-of-the-box "DVR to ZoneMinder bridge" turned out to fall short of that.
